"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useCallback, useEffect, useState } from "react";

type PartnerSubmission = { id: string; organization_id: string; entity_type: string; payload: Record<string, any>; status: string; review_note: string | null; updated_at: string };
type PartnerData = { user: { email?: string }; memberships: Array<{ organization_id: string; member_role: string; organizations: { name_ar: string; slug: string } | null }>; submissions: PartnerSubmission[]; products: Array<{ id: string; name_ar: string; product_kind: string }>; categories: Array<{ id: string; code: string; name_ar: string; parent_id: string | null }> };

export function PartnerPortal() {
  const [state,setState]=useState<"loading"|"signed_out"|"ready"|"error">("loading");
  const [data,setData]=useState<PartnerData|null>(null);
  const [message,setMessage]=useState("");
  const [entityType,setEntityType]=useState("product_offer");
  const [working,setWorking]=useState(false);
  const [queued,setQueued]=useState(0);
  const queueKey="qahwatna-partner-offline-v1";
  const load=useCallback(async()=>{const response=await fetch("/api/partner/submissions",{cache:"no-store"});if(response.status===401){setState("signed_out");setData(null);return;}const payload=await response.json();if(!response.ok)throw new Error("load_failed");setData(payload);setState("ready");},[]);
  const readQueue=useCallback(()=>{try{return JSON.parse(localStorage.getItem(queueKey)||"[]") as any[];}catch{return [];}},[]);
  const writeQueue=useCallback((items:any[])=>{localStorage.setItem(queueKey,JSON.stringify(items));setQueued(items.length);},[]);
  const send=useCallback(async(item:any)=>{const response=await fetch("/api/partner/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(item)});if(!response.ok)throw new Error(String(response.status));return response.json();},[]);
  const flush=useCallback(async()=>{if(!navigator.onLine)return;const items=readQueue();if(!items.length)return;const remaining=[];for(const item of items){try{await send(item);}catch{remaining.push(item);}}writeQueue(remaining);if(remaining.length===0){setMessage("تمت مزامنة الطلبات المحفوظة على الجهاز.");await load();}},[load,readQueue,send,writeQueue]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setQueued(readQueue().length);load().catch(()=>setState("error"));},0);const online=()=>flush();window.addEventListener("online",online);return()=>{window.clearTimeout(timer);window.removeEventListener("online",online);};},[flush,load,readQueue]);
  const login=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/partner/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});if(!response.ok){const result=await response.json().catch(()=>({}));setMessage(result.reason==="active_membership_required"?"الحساب صحيح، لكن عضوية الجهة لم تُفعّل بعد.":"تعذر الدخول. تحقق من البريد وكلمة المرور.");return;}setState("loading");await load();};
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!data?.memberships[0])return;const formElement=event.currentTarget;const form=new FormData(formElement);const payload:Record<string,unknown>=entityType==="organization_update"?{name_ar:form.get("name_ar"),phone:form.get("phone"),email:form.get("email"),website_url:form.get("website_url"),description_ar:form.get("description_ar")} : entityType==="location"?{name_ar:form.get("name_ar"),address_ar:form.get("address_ar"),district_ar:form.get("district_ar"),phone:form.get("phone")} : entityType==="product_offer"?{product_id:form.get("product_id"),price:form.get("price"),currency_code:"IQD",availability:form.get("availability"),external_url:form.get("evidence_url"),observed_at:new Date().toISOString(),source_label:"بوابة الجهة المشاركة",source_type:"organization"} : {name_ar:form.get("name_ar"),name_en:form.get("name_en"),product_kind:form.get("product_kind"),category_id:form.get("category_id"),model_number:form.get("model_number"),summary_ar:form.get("summary_ar"),source_label:"بوابة الجهة المشاركة",source_type:"organization"};
    const item={organizationId:data.memberships[0].organization_id,entityType,payload,idempotencyKey:crypto.randomUUID(),clientUpdatedAt:new Date().toISOString(),status:"submitted"};setWorking(true);setMessage("جارٍ إرسال الطلب للمراجعة…");try{await send(item);setMessage("تم الإرسال. لن يظهر التغيير للعامة إلا بعد مراجعة فريق قهوتنا.");formElement.reset();await load();}catch{const items=readQueue();items.push(item);writeQueue(items);setMessage("الشبكة غير مستقرة؛ حُفظ الطلب على هذا الجهاز وسيُرسل تلقائياً عند عودة الاتصال.");}finally{setWorking(false);}};
  const statusLabel:Record<string,string>={draft:"مسودة",submitted:"مرسل للمراجعة",in_review:"قيد المراجعة",needs_changes:"يحتاج تعديلاً",approved:"معتمد",rejected:"مرفوض",archived:"مؤرشف"};
  if(state==="loading")return <section className="partner-portal"><p role="status">جارٍ فحص حساب الجهة…</p></section>;
  if(state==="error")return <section className="partner-portal directory-state"><h2>تعذر تحميل بوابة الجهة</h2><button onClick={()=>{setState("loading");load().catch(()=>setState("error"));}}>إعادة المحاولة</button></section>;
  if(state==="signed_out")return <section className="partner-portal"><form className="admin-login" onSubmit={login}><b>الدخول بحساب الجهة أو البائع</b><p>الحساب يحتاج عضوية جهة مفعلة من إدارة قهوتنا.</p><label>البريد الإلكتروني<input name="email" type="email" autoComplete="username" required /></label><label>كلمة المرور<input name="password" type="password" autoComplete="current-password" minLength={8} required /></label><button className="primary" type="submit">دخول بوابة الجهة</button>{message&&<p role="status">{message}</p>}</form></section>;
  const membership=data!.memberships[0];
  return <section className="partner-portal"><div className="section-head"><div><span className="eyebrow">بوابة خاضعة للمراجعة</span><h2>{membership.organizations?.name_ar||"الجهة المشاركة"}</h2><p>{data!.user.email} · {membership.member_role}</p></div><button type="button" onClick={async()=>{await fetch("/api/partner/logout",{method:"POST"});setState("signed_out");setData(null);}}>تسجيل الخروج</button></div><div className="partner-safety"><b>لا يوجد نشر مباشر</b><span>كل تعديل يُحفظ كطلب مستقل، يراجعه فريق قهوتنا، ثم يُعتمد أو يعاد إليك بملاحظة.</span>{queued>0&&<button type="button" onClick={flush}>{queued} طلب بانتظار المزامنة</button>}</div>
    <form className="partner-submission-form" onSubmit={submit}><label>طبيعة الإدخال<select value={entityType} onChange={e=>setEntityType(e.target.value)}><option value="product_offer">منتج موجود لدى بائع: سعر وتوفر</option><option value="new_product">اقتراح بطاقة منتج رئيسية جديدة</option><option value="organization_update">تحديث معلومات الجهة</option><option value="location">إضافة موقع أو فرع في بغداد</option></select></label>
    {entityType==="product_offer"&&<><label>المنتج الرئيسي<select name="product_id" required><option value="">اختر المنتج</option>{data!.products.map(p=><option key={p.id} value={p.id}>{p.name_ar}</option>)}</select></label><label>السعر بالدينار العراقي<input name="price" type="number" min="0" step="1" required /></label><label>التوفر<select name="availability"><option value="in_stock">متوفر</option><option value="out_of_stock">غير متوفر</option><option value="preorder">طلب مسبق</option><option value="unknown">غير متحقق</option></select></label><label className="wide">رابط دليل السعر أو التوفر<input name="evidence_url" type="url" required /></label></>}
    {entityType==="new_product"&&<><label>الاسم العربي<input name="name_ar" required minLength={2}/></label><label>الاسم الإنجليزي<input name="name_en" /></label><label>قسم المنتج<select name="product_kind" required><option value="roasted_coffee">قهوة محمصة</option><option value="equipment">معدات</option><option value="consumable">مستهلكات</option><option value="care_product">عناية وصيانة</option><option value="replacement_part">قطع غيار</option></select></label><label>الفئة الدقيقة<select name="category_id" required><option value="">اختر الفئة</option>{data!.categories.filter(c=>c.parent_id).map(c=><option key={c.id} value={c.id}>{c.name_ar}</option>)}</select></label><label>الموديل<input name="model_number" /></label><label className="wide">ملخص المنتج<textarea name="summary_ar" /></label></>}
    {entityType==="organization_update"&&<><label>اسم الجهة<input name="name_ar" defaultValue={membership.organizations?.name_ar||""} required /></label><label>الهاتف<input name="phone" /></label><label>البريد<input name="email" type="email" /></label><label>الموقع الرسمي إن وجد<input name="website_url" type="url" /></label><label className="wide">الوصف<textarea name="description_ar" /></label></>}
    {entityType==="location"&&<><label>اسم الفرع<input name="name_ar" /></label><label>المنطقة<input name="district_ar" required /></label><label className="wide">العنوان في بغداد<input name="address_ar" required minLength={3}/></label><label>هاتف الفرع<input name="phone" /></label></>}
    <button className="primary wide" type="submit" disabled={working}>{working?"جارٍ الحفظ…":"إرسال للمراجعة"}</button>{message&&<p className="admin-message wide" role="status">{message}</p>}</form>
    <section className="partner-history"><div className="section-head"><div><span className="eyebrow">سجل شفاف</span><h3>طلبات الجهة</h3></div><span>{data!.submissions.length}</span></div>{data!.submissions.map(row=><article key={row.id}><div><b>{({product_offer:"عرض منتج",new_product:"منتج رئيسي جديد",organization_update:"تحديث جهة",location:"فرع أو موقع"} as Record<string,string>)[row.entity_type]||row.entity_type}</b><span>{new Date(row.updated_at).toLocaleString("ar-IQ")}</span></div><div><strong>{statusLabel[row.status]||row.status}</strong>{row.review_note&&<small>{row.review_note}</small>}</div></article>)}{!data!.submissions.length&&<p>لا توجد طلبات بعد.</p>}</section></section>;
}

