-- Coffee Platform V1 — taxonomy and filter reference seed
-- Version: 1.1.0 compact | Date: 2026-08-09
-- Requires migration 001. Safe to rerun: records are upserted by stable codes.
begin;
do $$ begin if to_regclass('public.categories') is null or to_regclass('public.field_definitions') is null then raise exception 'Migration 001 must be run before 002'; end if; end $$;
alter table public.roaster_specifications drop constraint if exists roaster_specifications_heat_source_check;
alter table public.roaster_specifications add constraint roaster_specifications_heat_source_check check (heat_source is null or heat_source in ('electric','natural_gas','lpg','dual_fuel','other_declared'));
with seed(code,parent_code,slug,name_ar,name_en,sort_order,comparison_group,phase,status) as (values
  ('COF',null,'coffee','القهوة','Coffee',10,null,'V1','published'),
  ('EQP',null,'equipment','المعدات','Equipment',20,null,'V1','published')
)
insert into public.categories (code,parent_id,slug,name_ar,name_en,sort_order,comparison_group,phase,is_filterable,status)
select s.code,p.id,s.slug,s.name_ar,s.name_en,s.sort_order,s.comparison_group,s.phase,true,s.status::public.publication_status
from seed s left join public.categories p on p.code=s.parent_code
on conflict (code) do update set parent_id=excluded.parent_id, slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort_order=excluded.sort_order, comparison_group=excluded.comparison_group, phase=excluded.phase, is_filterable=excluded.is_filterable, status=excluded.status;
with seed(code,parent_code,slug,name_ar,name_en,sort_order,comparison_group,phase,status) as (values
  ('COF-ROASTED','COF','roasted-coffee','القهوة المحمصة','Roasted Coffee',10,'roasted_coffee','V1','published'),
  ('COF-GREEN','COF','green-coffee','القهوة الخضراء','Green Coffee',20,'green_coffee','Phase 2 Professional','draft'),
  ('EQP-GRD','EQP','grinders','المطاحن','Grinders',10,null,'V1','published'),
  ('EQP-MCH','EQP','coffee-machines','آلات القهوة','Coffee Machines',20,null,'V1','published'),
  ('EQP-BRW','EQP','manual-brewers','أدوات التحضير اليدوي','Manual Brewers',30,null,'V1','published'),
  ('EQP-KET','EQP','kettles','الغلايات','Kettles',40,null,'V1','published'),
  ('EQP-MSR','EQP','scales-measuring','الموازين والقياس','Scales & Measuring',50,null,'V1','published'),
  ('EQP-ESP','EQP','espresso-tools','أدوات الإسبريسو','Espresso Tools',60,null,'V1','published'),
  ('EQP-FIL','EQP','filters-consumables','الفلاتر والمستهلكات','Filters & Consumables',70,null,'V1','published'),
  ('EQP-SRV','EQP','servers-carafes','أدوات التقديم','Servers & Carafes',80,null,'V1','published'),
  ('EQP-WCS','EQP','water-care-storage','الماء والعناية والتخزين','Water, Care & Storage',90,null,'V1','published'),
  ('EQP-ROA','EQP','roasting-machines','مكائن التحميص','Roasting Machines',100,null,'V1','published')
)
insert into public.categories (code,parent_id,slug,name_ar,name_en,sort_order,comparison_group,phase,is_filterable,status)
select s.code,p.id,s.slug,s.name_ar,s.name_en,s.sort_order,s.comparison_group,s.phase,true,s.status::public.publication_status
from seed s left join public.categories p on p.code=s.parent_code
on conflict (code) do update set parent_id=excluded.parent_id, slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort_order=excluded.sort_order, comparison_group=excluded.comparison_group, phase=excluded.phase, is_filterable=excluded.is_filterable, status=excluded.status;
with seed(code,parent_code,slug,name_ar,name_en,sort_order,comparison_group,phase,status) as (values
  ('EQP-GRD-MAN','EQP-GRD','manual-grinders','مطاحن يدوية','Manual Grinders',10,'manual_grinders','V1','published'),
  ('EQP-GRD-ELE','EQP-GRD','electric-grinders','مطاحن كهربائية','Electric Grinders',20,'electric_grinders','V1','published'),
  ('EQP-MCH-ESP','EQP-MCH','espresso-machines','آلات الإسبريسو','Espresso Machines',10,'espresso_machines','V1','published'),
  ('EQP-MCH-FLT','EQP-MCH','filter-coffee-machines','آلات القهوة المفلترة','Filter Coffee Machines',20,'filter_coffee_machines','V1','published'),
  ('EQP-MCH-TRK','EQP-MCH','turkish-coffee-machines','آلات القهوة التركية','Turkish Coffee Machines',30,'turkish_coffee_machines','V1','published'),
  ('EQP-MCH-CAP','EQP-MCH','capsule-pod-machines','آلات الكبسولات','Capsule & Pod Machines',40,'capsule_machines','V1','published'),
  ('EQP-BRW-DRP','EQP-BRW','pour-over-drippers','مرشحات التقطير','Pour-over Drippers',10,'pour_over_drippers','V1','published'),
  ('EQP-BRW-FRP','EQP-BRW','french-presses','فرنش بريس','French Presses',20,'french_presses','V1','published'),
  ('EQP-BRW-PRS','EQP-BRW','manual-press-brewers','مكابس يدوية','Manual Press Brewers',30,'manual_press_brewers','V1','published'),
  ('EQP-BRW-INT','EQP-BRW','integrated-pour-over-brewers','أدوات ترشيح مدمجة','Integrated Pour-over Brewers',40,'integrated_brewers','V1','published'),
  ('EQP-BRW-MOK','EQP-BRW','moka-pots','موكا بوت','Moka Pots',50,'moka_pots','V1','published'),
  ('EQP-BRW-SYP','EQP-BRW','syphon-brewers','سايفون','Vacuum Brewers / Syphons',60,'syphon_brewers','V1','published'),
  ('EQP-BRW-CLD','EQP-BRW','cold-brew-makers','أدوات كولد برو','Cold Brew Makers',70,'cold_brew_makers','V1','published'),
  ('EQP-BRW-IBR','EQP-BRW','cezve-ibrik','ركوة وجزوة','Cezve & Ibrik',80,'cezve_ibrik','V1','published'),
  ('EQP-BRW-SIF','EQP-BRW','south-indian-filters','فلاتر جنوب الهند','South Indian Filters',90,'south_indian_filters','V1','published'),
  ('EQP-BRW-PHN','EQP-BRW','vietnamese-phin','فلاتر فيتنامية Phin','Vietnamese Phin',100,'vietnamese_phin','V1','published'),
  ('EQP-KET-ELE','EQP-KET','electric-kettles','غلايات كهربائية','Electric Kettles',10,'electric_kettles','V1','published'),
  ('EQP-KET-STV','EQP-KET','stovetop-kettles','غلايات للموقد','Stovetop Kettles',20,'stovetop_kettles','V1','published'),
  ('EQP-MSR-SCL','EQP-MSR','coffee-scales','موازين القهوة','Coffee Scales',10,'coffee_scales','V1','published'),
  ('EQP-MSR-THM','EQP-MSR','thermometers','مقاييس الحرارة','Thermometers',20,'thermometers','V1','published'),
  ('EQP-MSR-REF','EQP-MSR','refractometers','مقاييس الانكسار','Refractometers',30,'refractometers','V1','published'),
  ('EQP-ESP-TMP','EQP-ESP','tampers','مكابس القهوة','Tampers',10,'tampers','V1','published'),
  ('EQP-ESP-DST','EQP-ESP','distribution-tools','أدوات توزيع البن','Distribution Tools',20,'distribution_tools','V1','published'),
  ('EQP-ESP-KBX','EQP-ESP','knock-boxes','صناديق تفريغ البن','Knock Boxes',30,'knock_boxes','V1','published'),
  ('EQP-ESP-PRT','EQP-ESP','portafilters-baskets','حوامل البورتافلتر والسلال','Portafilters & Baskets',40,'portafilters_baskets','V1','published'),
  ('EQP-ESP-MIL','EQP-ESP','milk-pitchers','أباريق الحليب','Milk Pitchers',50,'milk_pitchers','V1','published'),
  ('EQP-ESP-DSG','EQP-ESP','dosing-cups-funnels','أكواب وقمع الجرعات','Dosing Cups & Funnels',60,'dosing_tools','V1','published'),
  ('EQP-ESP-PCK','EQP-ESP','puck-screens','شاشات القرص','Puck Screens',70,'puck_screens','V1','published'),
  ('EQP-ESP-MAT','EQP-ESP','tamping-mats','حصائر الكبس','Tamping Mats',80,'tamping_mats','V1','published'),
  ('EQP-ESP-MIR','EQP-ESP','shot-mirrors','مرايا الاستخلاص','Shot Mirrors',90,'shot_mirrors','V1','published'),
  ('EQP-FIL-PAP','EQP-FIL','paper-filters','فلاتر ورقية','Paper Filters',10,'paper_filters','V1','published'),
  ('EQP-FIL-MET','EQP-FIL','metal-filters','فلاتر معدنية','Metal Filters',20,'metal_filters','V1','published'),
  ('EQP-FIL-CLT','EQP-FIL','cloth-filters','فلاتر قماشية','Cloth Filters',30,'cloth_filters','V1','published'),
  ('EQP-FIL-CAP','EQP-FIL','refillable-capsules','كبسولات قابلة لإعادة التعبئة','Refillable Capsules',40,'refillable_capsules','V1','published'),
  ('EQP-SRV-SRV','EQP-SRV','coffee-servers','سيرفرات قهوة','Coffee Servers',10,'coffee_servers','V1','published'),
  ('EQP-SRV-THM','EQP-SRV','thermal-carafes','حافظات حرارية','Thermal Carafes',20,'thermal_carafes','V1','published'),
  ('EQP-WCS-WAT','EQP-WCS','water-treatment','معالجة الماء','Water Treatment',10,'water_treatment','V1','published'),
  ('EQP-WCS-CLN','EQP-WCS','cleaning-maintenance','التنظيف والصيانة','Cleaning & Maintenance',20,'cleaning_maintenance','V1','published'),
  ('EQP-WCS-STR','EQP-WCS','coffee-storage','تخزين القهوة','Coffee Storage',30,'coffee_storage','V1','published'),
  ('EQP-ROA-HOM','EQP-ROA','home-coffee-roasters','مكائن تحميص منزلية','Home Coffee Roasters',10,'roaster_home','V1','published'),
  ('EQP-ROA-SMP','EQP-ROA','sample-roasters','مكائن تحميص العينات','Sample Roasters',20,'roaster_sample','V1','published'),
  ('EQP-ROA-COM','EQP-ROA','commercial-batch-roasters','مكائن تحميص تجارية بالدفعات','Commercial Batch Roasters',30,'roaster_commercial','V1','published')
)
insert into public.categories (code,parent_id,slug,name_ar,name_en,sort_order,comparison_group,phase,is_filterable,status)
select s.code,p.id,s.slug,s.name_ar,s.name_en,s.sort_order,s.comparison_group,s.phase,true,s.status::public.publication_status
from seed s left join public.categories p on p.code=s.parent_code
on conflict (code) do update set parent_id=excluded.parent_id, slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort_order=excluded.sort_order, comparison_group=excluded.comparison_group, phase=excluded.phase, is_filterable=excluded.is_filterable, status=excluded.status;
with seed(code,parent_code,slug,name_ar,name_en,sort_order,comparison_group,phase,status) as (values
  ('EQP-ESP-WDT','EQP-ESP-DST','wdt-tools','أدوات WDT','WDT Tools',10,'wdt_tools','V1','published')
)
insert into public.categories (code,parent_id,slug,name_ar,name_en,sort_order,comparison_group,phase,is_filterable,status)
select s.code,p.id,s.slug,s.name_ar,s.name_en,s.sort_order,s.comparison_group,s.phase,true,s.status::public.publication_status
from seed s left join public.categories p on p.code=s.parent_code
on conflict (code) do update set parent_id=excluded.parent_id, slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort_order=excluded.sort_order, comparison_group=excluded.comparison_group, phase=excluded.phase, is_filterable=excluded.is_filterable, status=excluded.status;
insert into public.field_definitions (code,name_ar,name_en,data_type,unit_code,allowed_values,validation_rules,missing_value_policy,is_searchable,is_comparable,is_recommendation_input,is_multi_value,status) values
  ('accuracy','الدقة','Accuracy','decimal','حسب النوع','[]'::jsonb,'{"rules":["مع وحدة وشروط القياس"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('adjustment','ضبط الطحن','Adjustment','enum',null,'["stepped","stepless","fixed"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["stepped|stepless|fixed"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('airflow_control','التحكم بتدفق الهواء','Airflow control','enum',null,'["fixed","manual_variable","automatic"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["fixed|manual_variable|automatic"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('application','الاستخدام','Application','multi_enum',null,'["home","office","commercial"]'::jsonb,'{"rules":["قيمة محكومة"],"raw_allowed":["home|office|commercial"],"accepted_source_types":["Manufacturer + editorial"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,true,'published'),
  ('auto_shutoff','إيقاف تلقائي','Auto shut-off','boolean',null,'["true","false"]'::jsonb,'{"rules":["لا يستنتج"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('availability','التوفر','Availability','enum',null,'["in_stock","out_of_stock","preorder","unknown"]'::jsonb,'{"rules":["لا استنتاج من وجود صفحة"],"raw_allowed":["in_stock|out_of_stock|preorder|unknown"],"accepted_source_types":["Verified seller offer"],"storage_binding":"offers.availability"}'::jsonb,'show_unknown',true,true,false,false,'published'),
  ('batch_capacity_max','الحد الأعلى لسعة الدفعة','Maximum batch capacity','decimal','kg','[]'::jsonb,'{"rules":["أكبر أو يساوي الحد الأدنى"],"raw_allowed":["0.05..500"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.batch_max_kg"}'::jsonb,'hide',true,true,true,false,'published'),
  ('batch_capacity_min','الحد الأدنى لسعة الدفعة','Minimum batch capacity','decimal','kg','[]'::jsonb,'{"rules":["أكبر من صفر ولا يتجاوز الحد الأعلى"],"raw_allowed":["0.05..500"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.batch_min_kg"}'::jsonb,'hide',true,true,true,false,'published'),
  ('brand_id','العلامة التجارية','Brand','reference',null,'[]'::jsonb,'{"rules":["مرجع منشور غير مكرر"],"raw_allowed":["Brand registry"],"accepted_source_types":["Manufacturer/official seller"],"storage_binding":"products.brand_id"}'::jsonb,'hide',true,true,true,false,'published'),
  ('brew_capacity_l','سعة التحضير','Brew capacity','decimal','L','[]'::jsonb,'{"rules":["تحويل موحد إلى لتر"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('brew_capacity_ml','السعة','Capacity','decimal','mL','[]'::jsonb,'{"rules":["تحويل موحد إلى mL"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('brew_methods','طرق التحضير','Brew methods','multi_enum',null,'["espresso","filter","turkish","moka_pot","french_press","cold_brew"]'::jsonb,'{"rules":["مفردات محكومة ولا تستنتج من التحميص","مفردات محكومة"],"raw_allowed":["espresso|filter|turkish|moka_pot|french_press|cold_brew"],"accepted_source_types":["Roaster + editorial review","Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,true,'published'),
  ('brewer_type','نوع أداة التحضير','Brewer type','reference',null,'[]'::jsonb,'{"rules":["فئة أساسية واحدة"],"raw_allowed":["Primary taxon"],"accepted_source_types":["Taxonomy"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('burr_geometry','هندسة الشفرات','Burr geometry','enum',null,'["flat","conical","not_applicable"]'::jsonb,'{"rules":["مطلوب عند burr"],"raw_allowed":["flat|conical|not_applicable"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('burr_mechanism','آلية الطحن','Grinding mechanism','enum',null,'["burr","blade","other"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["burr|blade|other"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('burr_size_mm','حجم الشفرات','Burr size','decimal','mm','[]'::jsonb,'{"rules":["ضمن النطاق ومصدر"],"raw_allowed":["10–150"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('caffeine_type','الكافيين','Caffeine','enum',null,'["regular","decaf","half_caf","unknown"]'::jsonb,'{"rules":["unknown حالة لا نفي"],"raw_allowed":["regular|decaf|half_caf|unknown"],"accepted_source_types":["Roaster"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('capacity_g','السعة القصوى','Maximum capacity','decimal','g','[]'::jsonb,'{"rules":["قيمة موجبة","تحويل موحد"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('capacity_l','السعة','Capacity','decimal','L','[]'::jsonb,'{"rules":["تحويل موحد"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('capacity_ml','السعة','Capacity','decimal','mL','[]'::jsonb,'{"rules":["تحويل موحد"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('capsule_system','نظام الكبسولة','Capsule system','reference',null,'[]'::jsonb,'{"rules":["مرجع توافق لا نص حر"],"raw_allowed":["Controlled compatibility registry"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('carafe_type','نوع الإبريق','Carafe type','enum',null,'["glass","thermal","none"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["glass|thermal|none"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('care_task','مهمة العناية','Care task','multi_enum',null,'["descaling","backflushing","grinder_cleaning","milk_system_cleaning","surface_cleaning","brush"]'::jsonb,'{"rules":["مفردات محكومة"],"raw_allowed":["descaling|backflushing|grinder_cleaning|milk_system_cleaning|surface_cleaning|brush"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,true,'published'),
  ('chaff_collection','جمع القشور','Chaff collection','enum',null,'["internal","external","cyclone","required_separate"]'::jsonb,'{"rules":["قيمة معلنة"],"raw_allowed":["internal|external|cyclone|required_separate"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,false,false,'published'),
  ('closure','آلية الإغلاق','Closure','enum',null,'["airtight","vacuum","valve","zip","other"]'::jsonb,'{"rules":["قيمة محكومة"],"raw_allowed":["airtight|vacuum|valve|zip|other"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('coffee_form','شكل القهوة','Coffee form','enum',null,'["whole","ground"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["whole|ground"],"accepted_source_types":["Roaster/seller"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('compatible_brewers','الأدوات المتوافقة','Compatible brewers','reference',null,'[]'::jsonb,'{"rules":["مرجع فعلي","علاقة فعلية"],"raw_allowed":["Compatibility registry"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_compatibilities"}'::jsonb,'block_publish',true,true,true,true,'published'),
  ('compatible_equipment','المعدات المتوافقة','Compatible equipment','reference',null,'[]'::jsonb,'{"rules":["مرجع فعلي"],"raw_allowed":["Compatibility registry"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_compatibilities"}'::jsonb,'hide',true,true,true,true,'published'),
  ('compatible_models','التوافق','Compatible models','reference',null,'[]'::jsonb,'{"rules":["علاقة لا نص حر"],"raw_allowed":["Compatibility registry"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('compatible_systems','الأنظمة المتوافقة','Compatible systems','reference',null,'[]'::jsonb,'{"rules":["مرجع فعلي"],"raw_allowed":["Compatibility registry"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_compatibilities"}'::jsonb,'hide',true,true,true,true,'published'),
  ('composition','التركيب','Composition','enum',null,'["single_origin","blend"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["single_origin|blend"],"accepted_source_types":["Roaster"],"storage_binding":"product_attribute_values"}'::jsonb,'lower_confidence',true,true,true,false,'published'),
  ('connectivity','الاتصال','Connectivity','multi_enum',null,'["none","bluetooth","wifi","usb"]'::jsonb,'{"rules":["مفردات محكومة"],"raw_allowed":["none|bluetooth|wifi|usb"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('control_mode','نمط التحكم','Control mode','multi_enum',null,'["manual","digital","profile_logging","automation"]'::jsonb,'{"rules":["مفردات محكومة متعددة"],"raw_allowed":["manual|digital|profile_logging|automation"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('cooling_system','نظام التبريد','Cooling system','multi_enum',null,'["tray_air","water_assist","integrated","external","other_declared"]'::jsonb,'{"rules":["مفردات محكومة"],"raw_allowed":["tray_air|water_assist|integrated|external|other_declared"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,false,true,'published'),
  ('cup_capacity','عدد الأكواب','Cup capacity','integer','cup','[]'::jsonb,'{"rules":["عدد صحيح"],"raw_allowed":["1–12"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('diameter_mm','القطر','Diameter','decimal','mm','[]'::jsonb,'{"rules":["مطلوب للأدوات المتوافقة مع البورتافلتر"],"raw_allowed":["20–80"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('dimensions','الأبعاد','Dimensions','json','mm','[]'::jsonb,'{"rules":["ثلاث قيم موجبة مع الوحدة"],"raw_allowed":["width|depth|height"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.dimensions_mm"}'::jsonb,'hide',false,true,false,false,'published'),
  ('drum_speed_control','التحكم بسرعة الأسطوانة','Drum speed control','enum',null,'["fixed","variable","not_applicable"]'::jsonb,'{"rules":["يتسق مع التقنية"],"raw_allowed":["fixed|variable|not_applicable"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('electrical_supply','التغذية الكهربائية','Electrical supply','json','V/Hz/phase','[]'::jsonb,'{"rules":["صيغة منظمة للجهد والتردد والطور"],"raw_allowed":["manufacturer-declared"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.power_supply"}'::jsonb,'hide',true,true,false,true,'published'),
  ('feeding','نظام التغذية','Feeding','enum',null,'["single_dose","hopper","both"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["single_dose|hopper|both"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('filter_material','المادة','Filter material','enum',null,'["paper","metal","cloth","polymer"]'::jsonb,'{"rules":["مطابق للفئة"],"raw_allowed":["paper|metal|cloth|polymer"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('filter_shape','الشكل','Filter shape','enum',null,'["cone","basket","disc","capsule","custom"]'::jsonb,'{"rules":["قيمة محكومة"],"raw_allowed":["cone|basket|disc|capsule|custom"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('filter_size','المقاس','Filter size','json',null,'[]'::jsonb,'{"rules":["مرتبط بنظام المقاس"],"raw_allowed":["Manufacturer sizing system"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('filter_type','نوع الفلتر','Filter type','multi_enum',null,'["paper","metal","cloth","none","capsule"]'::jsonb,'{"rules":["التوافق بعلاقة مستقلة"],"raw_allowed":["paper|metal|cloth|none|capsule"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('flavor_family','عائلة النكهة','Flavor family','multi_enum',null,'["chocolate_cocoa","sweet_caramel","nutty","fruity","floral_tea"]'::jsonb,'{"rules":["لا إنشاء عائلات جديدة"],"raw_allowed":["chocolate_cocoa|sweet_caramel|nutty|fruity|floral_tea"],"accepted_source_types":["Roaster + controlled mapping"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('flow_rate','قياس معدل التدفق','Flow-rate','boolean',null,'["true","false"]'::jsonb,'{"rules":["خاصية موثقة"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('gas_requirement','متطلبات الغاز','Gas requirement','text',null,'[]'::jsonb,'{"rules":["يطلب فقط للأجهزة الغازية"],"raw_allowed":["manufacturer-declared"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.gas_type"}'::jsonb,'hide',false,true,false,false,'published'),
  ('gooseneck','عنق الإوزة','Gooseneck','boolean',null,'["true","false"]'::jsonb,'{"rules":["لا يستنتج"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('grinder_drive','نمط التشغيل','Drive','enum',null,'["manual","electric"]'::jsonb,'{"rules":["مطابق للفئة"],"raw_allowed":["manual|electric"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('group_count','عدد المجموعات','Group count','integer','group','[]'::jsonb,'{"rules":["عدد صحيح"],"raw_allowed":["1–4"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('heat_source','مصدر الحرارة','Heat source','enum',null,'["electric","natural_gas","lpg","dual_fuel","other_declared"]'::jsonb,'{"rules":["قيمة واحدة موثقة"],"raw_allowed":["electric|natural_gas|lpg|dual_fuel|other_declared"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.heat_source"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('heating_system','نظام التسخين','Heating system','multi_enum',null,'["thermoblock","single_boiler","heat_exchanger","dual_boiler","multi_boiler"]'::jsonb,'{"rules":["مصطلحات محكومة"],"raw_allowed":["thermoblock|single_boiler|heat_exchanger|dual_boiler|multi_boiler"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('installation_required','يتطلب تركيباً متخصصاً','Professional installation required','boolean',null,'["true","false","unknown"]'::jsonb,'{"rules":["لا يقدم كإرشاد تركيب"],"raw_allowed":["true|false|unknown"],"accepted_source_types":["Manufacturer/manual"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('insulated','معزول','Insulated','boolean',null,'["true","false"]'::jsonb,'{"rules":["لا يستنتج"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('kettle_drive','مصدر التسخين','Heating source','enum',null,'["electric","stovetop"]'::jsonb,'{"rules":["مطابق للفئة"],"raw_allowed":["electric|stovetop"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('local_service_available','صيانة محلية متاحة','Local service available','boolean',null,'["true","false","unknown"]'::jsonb,'{"rules":["لا تحول unknown إلى false"],"raw_allowed":["true|false|unknown"],"accepted_source_types":["Verified service provider"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('market_price','السعر','Price','decimal','ISO 4217','[]'::jsonb,'{"rules":["مع سوق وعملة وobserved_at"],"raw_allowed":[">=0"],"accepted_source_types":["Verified seller offer"],"storage_binding":"offers.price"}'::jsonb,'hide',false,true,false,false,'published'),
  ('material','المادة','Material','multi_enum',null,'["plastic","glass","ceramic","metal","cloth","wood","composite","stainless_steel","aluminum","rubber","silicone"]'::jsonb,'{"rules":["مفردات محكومة"],"raw_allowed":["plastic|glass|ceramic|metal|cloth|wood|composite","stainless_steel|aluminum|wood|rubber|silicone|plastic|glass","glass|stainless_steel|plastic|ceramic"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,false,true,'published'),
  ('measurement_range','نطاق القياس','Measurement range','json','حسب النوع','[]'::jsonb,'{"rules":["الوحدة متوافقة مع النوع"],"raw_allowed":["manufacturer stated"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('measurement_type','نوع القياس','Measurement type','enum',null,'["temperature","brix","tds","extraction_yield"]'::jsonb,'{"rules":["مطابق للجهاز"],"raw_allowed":["temperature|brix|tds|extraction_yield"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('milk_system','نظام الحليب','Milk system','enum',null,'["steam_wand","automatic","external","none","integrated"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["steam_wand|automatic|external|none","integrated|external|steam_wand|none"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('net_weight','الوزن الصافي','Net weight','decimal','kg','[]'::jsonb,'{"rules":["رقم موجب"],"raw_allowed":["0..10000"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"roaster_specifications.weight_kg"}'::jsonb,'hide',false,true,false,false,'published'),
  ('operation_mode','نمط التشغيل','Operation mode','enum',null,'["manual","semi_automatic","volumetric","automatic","super_automatic"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["manual|semi_automatic|volumetric|automatic|super_automatic"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('origin_ids','المنشأ','Origin','reference',null,'[]'::jsonb,'{"rules":["يعرض أدق مستوى موثق فقط"],"raw_allowed":["Country/Region/Farm/Lot"],"accepted_source_types":["SourceRecord"],"storage_binding":"origin_claims"}'::jsonb,'hide',true,true,true,true,'published'),
  ('pot_material','مادة الإبريق','Pot material','enum',null,'["stainless_steel","aluminum","copper","coated","other"]'::jsonb,'{"rules":["قيمة محكومة"],"raw_allowed":["stainless_steel|aluminum|copper|coated|other"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',false,true,false,false,'published'),
  ('process_codes','طرق المعالجة','Processing methods','multi_enum',null,'[]'::jsonb,'{"rules":["رمز محكوم ومصدر"],"raw_allowed":["controlled processing vocabulary"],"accepted_source_types":["Roaster/origin record"],"storage_binding":"origin_claims.process_code"}'::jsonb,'hide',true,true,true,true,'published'),
  ('product_form','صيغة المنتج','Product form','enum',null,'["powder","tablet","liquid","brush","cloth","tool"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["powder|tablet|liquid|brush|cloth|tool"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('profile_connectivity','الاتصال وتسجيل الملفات','Profile connectivity','multi_enum',null,'["usb","bluetooth","wifi","ethernet","api","none"]'::jsonb,'{"rules":["لا تستنتج من وجود شاشة"],"raw_allowed":["usb|bluetooth|wifi|ethernet|api|none"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('programmable','قابلة للبرمجة','Programmable','boolean',null,'["true","false"]'::jsonb,'{"rules":["لا يستنتج"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('rated_capacity_l','السعة المعالجة','Rated capacity','decimal','L','[]'::jsonb,'{"rules":["مع شروط المصدر"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('rated_power','القدرة الاسمية','Rated power','decimal','kW','[]'::jsonb,'{"rules":["رقم موجب ووحدة موحدة"],"raw_allowed":["0..1000"],"accepted_source_types":["Manufacturer datasheet"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',false,true,false,false,'published'),
  ('resolution_g','دقة القراءة','Resolution','decimal','g','[]'::jsonb,'{"rules":["قيمة موجبة"],"raw_allowed":[">0 and <=10"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('reusable','قابل لإعادة الاستخدام','Reusable','boolean',null,'["true","false"]'::jsonb,'{"rules":["لا يستنتج"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('roast_level_declared','مستوى التحميص المعلن','Declared roast level','enum',null,'["light","medium_light","medium","medium_dark","dark","other_declared"]'::jsonb,'{"rules":["ادعاء معلن لا قياس داخلي"],"raw_allowed":["light|medium_light|medium|medium_dark|dark|other_declared"],"accepted_source_types":["Roaster"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('roast_purpose','غرض التحميص المعلن','Declared roast purpose','enum',null,'["filter","espresso","omni","other_declared"]'::jsonb,'{"rules":["لا تعيد المنصة تصنيفه"],"raw_allowed":["filter|espresso|omni|other_declared"],"accepted_source_types":["Roaster"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('roaster_org_id','المحمصة','Roaster','reference',null,'[]'::jsonb,'{"rules":["دور roaster فعال"],"raw_allowed":["Verified organization"],"accepted_source_types":["Organization registry"],"storage_binding":"products.owner_organization_id"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('roaster_technology','تقنية التحميص','Roasting technology','enum',null,'["drum","fluid_bed","hybrid","other_declared"]'::jsonb,'{"rules":["قيمة معلنة موثقة"],"raw_allowed":["drum|fluid_bed|hybrid|other_declared"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('roaster_use_class','فئة الاستخدام','Roaster use class','enum',null,'["home","sample","commercial_batch"]'::jsonb,'{"rules":["تطابق الفئة الأساسية"],"raw_allowed":["home|sample|commercial_batch"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('sca_certified','اعتماد SCA موثق','SCA certified','json',null,'[]'::jsonb,'{"rules":["يتطلب رابطاً وتاريخ تحقق"],"raw_allowed":["true with current listing|false|unknown"],"accepted_source_types":["SCA official listing"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,false,false,'published'),
  ('servings','عدد الحصص','Servings','json','serving','[]'::jsonb,'{"rules":["نطاق صحيح"],"raw_allowed":["min 1"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('spare_parts_available','قطع الغيار متاحة','Spare parts available','enum',null,'["verified_available","seller_claim","unknown"]'::jsonb,'{"rules":["مع تاريخ تحقق"],"raw_allowed":["verified_available|seller_claim|unknown"],"accepted_source_types":["Supplier/source record"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('storage_type','نوع التخزين','Storage type','enum',null,'["canister","vacuum_canister","bag","dispenser","freezer_container"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["canister|vacuum_canister|bag|dispenser|freezer_container"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('temperature_control','التحكم بالحرارة','Temperature control','enum',null,'["none","preset","variable"]'::jsonb,'{"rules":["قيمة واحدة"],"raw_allowed":["none|preset|variable"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('temperature_range_c','نطاق الحرارة','Temperature range','json','°C','[]'::jsonb,'{"rules":["مطلوب للضبط المتغير"],"raw_allowed":["0–100"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('timer','مؤقت','Timer','boolean',null,'["true","false"]'::jsonb,'{"rules":["لا يستنتج"],"raw_allowed":["true|false"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'show_unknown',true,true,true,false,'published'),
  ('tool_type','نوع الأداة','Tool type','reference',null,'[]'::jsonb,'{"rules":["فئة أساسية واحدة"],"raw_allowed":["Primary taxon"],"accepted_source_types":["Taxonomy"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,false,'published'),
  ('warranty_months','مدة الضمان','Warranty period','integer','month','[]'::jsonb,'{"rules":["خاص بالسوق والبائع وتاريخ التحقق"],"raw_allowed":["0..120"],"accepted_source_types":["Supplier/manufacturer"],"storage_binding":"roaster_specifications.warranty_months"}'::jsonb,'hide',true,true,false,false,'published'),
  ('water_capacity_l','سعة الماء','Water capacity','decimal','L','[]'::jsonb,'{"rules":["تحويل موحد"],"raw_allowed":[">0"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,false,'published'),
  ('water_source','مصدر الماء','Water source','multi_enum',null,'["reservoir","plumbed","both"]'::jsonb,'{"rules":["مطابقة المواصفة"],"raw_allowed":["reservoir|plumbed|both"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'hide',true,true,true,true,'published'),
  ('water_task','المهمة','Water treatment task','multi_enum',null,'["filtration","softening","mineralization","testing","scale_control"]'::jsonb,'{"rules":["مفردات محكومة"],"raw_allowed":["filtration|softening|mineralization|testing|scale_control"],"accepted_source_types":["Manufacturer"],"storage_binding":"product_attribute_values"}'::jsonb,'block_publish',true,true,true,true,'published')
on conflict (code) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, data_type=excluded.data_type, unit_code=excluded.unit_code, allowed_values=excluded.allowed_values, validation_rules=excluded.validation_rules, missing_value_policy=excluded.missing_value_policy, is_searchable=excluded.is_searchable, is_comparable=excluded.is_comparable, is_recommendation_input=excluded.is_recommendation_input, is_multi_value=excluded.is_multi_value, status=excluded.status;
with seed(category_code,field_code,operator,sort_order,is_visible,is_required_for_publish) as (values
  ('COF-ROASTED','coffee_form','equals',10,true,true),
  ('COF-ROASTED','brew_methods','in',11,true,true),
  ('COF-ROASTED','roast_purpose','equals',12,true,false),
  ('COF-ROASTED','composition','equals',13,true,true),
  ('COF-ROASTED','origin_ids','in',14,true,false),
  ('COF-ROASTED','process_codes','in',15,true,false),
  ('COF-ROASTED','roast_level_declared','equals',16,true,false),
  ('COF-ROASTED','flavor_family','in',17,true,false),
  ('COF-ROASTED','caffeine_type','equals',18,true,false),
  ('COF-ROASTED','roaster_org_id','equals',19,true,true),
  ('EQP-BRW-CLD','brand_id','equals',1,true,false),
  ('EQP-BRW-CLD','brewer_type','equals',10,true,true),
  ('EQP-BRW-CLD','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-CLD','material','in',12,true,false),
  ('EQP-BRW-CLD','filter_type','in',13,true,false),
  ('EQP-BRW-CLD','servings','contains',14,true,false),
  ('EQP-BRW-CLD','market_price','range',90,true,false),
  ('EQP-BRW-CLD','availability','equals',91,true,false),
  ('EQP-BRW-DRP','brand_id','equals',1,true,false),
  ('EQP-BRW-DRP','brewer_type','equals',10,true,true),
  ('EQP-BRW-DRP','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-DRP','material','in',12,true,false),
  ('EQP-BRW-DRP','filter_type','in',13,true,false),
  ('EQP-BRW-DRP','servings','contains',14,true,false),
  ('EQP-BRW-DRP','market_price','range',90,true,false),
  ('EQP-BRW-DRP','availability','equals',91,true,false),
  ('EQP-BRW-FRP','brand_id','equals',1,true,false),
  ('EQP-BRW-FRP','brewer_type','equals',10,true,true),
  ('EQP-BRW-FRP','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-FRP','material','in',12,true,false),
  ('EQP-BRW-FRP','filter_type','in',13,true,false),
  ('EQP-BRW-FRP','servings','contains',14,true,false),
  ('EQP-BRW-FRP','market_price','range',90,true,false),
  ('EQP-BRW-FRP','availability','equals',91,true,false),
  ('EQP-BRW-IBR','brand_id','equals',1,true,false),
  ('EQP-BRW-IBR','brewer_type','equals',10,true,true),
  ('EQP-BRW-IBR','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-IBR','material','in',12,true,false),
  ('EQP-BRW-IBR','filter_type','in',13,true,false),
  ('EQP-BRW-IBR','servings','contains',14,true,false),
  ('EQP-BRW-IBR','market_price','range',90,true,false),
  ('EQP-BRW-IBR','availability','equals',91,true,false),
  ('EQP-BRW-INT','brand_id','equals',1,true,false),
  ('EQP-BRW-INT','brewer_type','equals',10,true,true),
  ('EQP-BRW-INT','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-INT','material','in',12,true,false),
  ('EQP-BRW-INT','filter_type','in',13,true,false),
  ('EQP-BRW-INT','servings','contains',14,true,false),
  ('EQP-BRW-INT','market_price','range',90,true,false),
  ('EQP-BRW-INT','availability','equals',91,true,false),
  ('EQP-BRW-MOK','brand_id','equals',1,true,false),
  ('EQP-BRW-MOK','brewer_type','equals',10,true,true),
  ('EQP-BRW-MOK','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-MOK','material','in',12,true,false),
  ('EQP-BRW-MOK','filter_type','in',13,true,false),
  ('EQP-BRW-MOK','servings','contains',14,true,false),
  ('EQP-BRW-MOK','market_price','range',90,true,false),
  ('EQP-BRW-MOK','availability','equals',91,true,false),
  ('EQP-BRW-PHN','brand_id','equals',1,true,false),
  ('EQP-BRW-PHN','brewer_type','equals',10,true,true),
  ('EQP-BRW-PHN','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-PHN','material','in',12,true,false),
  ('EQP-BRW-PHN','filter_type','in',13,true,false),
  ('EQP-BRW-PHN','servings','contains',14,true,false),
  ('EQP-BRW-PHN','market_price','range',90,true,false),
  ('EQP-BRW-PHN','availability','equals',91,true,false),
  ('EQP-BRW-PRS','brand_id','equals',1,true,false),
  ('EQP-BRW-PRS','brewer_type','equals',10,true,true),
  ('EQP-BRW-PRS','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-PRS','material','in',12,true,false),
  ('EQP-BRW-PRS','filter_type','in',13,true,false),
  ('EQP-BRW-PRS','servings','contains',14,true,false),
  ('EQP-BRW-PRS','market_price','range',90,true,false),
  ('EQP-BRW-PRS','availability','equals',91,true,false),
  ('EQP-BRW-SIF','brand_id','equals',1,true,false),
  ('EQP-BRW-SIF','brewer_type','equals',10,true,true),
  ('EQP-BRW-SIF','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-SIF','material','in',12,true,false),
  ('EQP-BRW-SIF','filter_type','in',13,true,false),
  ('EQP-BRW-SIF','servings','contains',14,true,false),
  ('EQP-BRW-SIF','market_price','range',90,true,false),
  ('EQP-BRW-SIF','availability','equals',91,true,false),
  ('EQP-BRW-SYP','brand_id','equals',1,true,false),
  ('EQP-BRW-SYP','brewer_type','equals',10,true,true),
  ('EQP-BRW-SYP','brew_capacity_ml','range',11,true,false),
  ('EQP-BRW-SYP','material','in',12,true,false),
  ('EQP-BRW-SYP','filter_type','in',13,true,false),
  ('EQP-BRW-SYP','servings','contains',14,true,false),
  ('EQP-BRW-SYP','market_price','range',90,true,false),
  ('EQP-BRW-SYP','availability','equals',91,true,false),
  ('EQP-ESP-DSG','brand_id','equals',1,true,false),
  ('EQP-ESP-DSG','tool_type','equals',10,true,true),
  ('EQP-ESP-DSG','diameter_mm','range',11,true,false),
  ('EQP-ESP-DSG','compatible_models','in',12,true,false),
  ('EQP-ESP-DSG','material','in',13,true,false),
  ('EQP-ESP-DSG','market_price','range',90,true,false),
  ('EQP-ESP-DSG','availability','equals',91,true,false),
  ('EQP-ESP-DST','brand_id','equals',1,true,false),
  ('EQP-ESP-DST','tool_type','equals',10,true,true),
  ('EQP-ESP-DST','diameter_mm','range',11,true,false),
  ('EQP-ESP-DST','compatible_models','in',12,true,false),
  ('EQP-ESP-DST','material','in',13,true,false),
  ('EQP-ESP-DST','market_price','range',90,true,false),
  ('EQP-ESP-DST','availability','equals',91,true,false),
  ('EQP-ESP-KBX','brand_id','equals',1,true,false),
  ('EQP-ESP-KBX','tool_type','equals',10,true,true),
  ('EQP-ESP-KBX','diameter_mm','range',11,true,false),
  ('EQP-ESP-KBX','compatible_models','in',12,true,false),
  ('EQP-ESP-KBX','material','in',13,true,false),
  ('EQP-ESP-KBX','market_price','range',90,true,false),
  ('EQP-ESP-KBX','availability','equals',91,true,false),
  ('EQP-ESP-MAT','brand_id','equals',1,true,false),
  ('EQP-ESP-MAT','tool_type','equals',10,true,true),
  ('EQP-ESP-MAT','diameter_mm','range',11,true,false),
  ('EQP-ESP-MAT','compatible_models','in',12,true,false),
  ('EQP-ESP-MAT','material','in',13,true,false),
  ('EQP-ESP-MAT','market_price','range',90,true,false),
  ('EQP-ESP-MAT','availability','equals',91,true,false),
  ('EQP-ESP-MIL','brand_id','equals',1,true,false),
  ('EQP-ESP-MIL','tool_type','equals',10,true,true),
  ('EQP-ESP-MIL','diameter_mm','range',11,true,false),
  ('EQP-ESP-MIL','compatible_models','in',12,true,false),
  ('EQP-ESP-MIL','material','in',13,true,false),
  ('EQP-ESP-MIL','market_price','range',90,true,false),
  ('EQP-ESP-MIL','availability','equals',91,true,false),
  ('EQP-ESP-MIR','brand_id','equals',1,true,false),
  ('EQP-ESP-MIR','tool_type','equals',10,true,true),
  ('EQP-ESP-MIR','diameter_mm','range',11,true,false),
  ('EQP-ESP-MIR','compatible_models','in',12,true,false),
  ('EQP-ESP-MIR','material','in',13,true,false),
  ('EQP-ESP-MIR','market_price','range',90,true,false),
  ('EQP-ESP-MIR','availability','equals',91,true,false),
  ('EQP-ESP-PCK','brand_id','equals',1,true,false),
  ('EQP-ESP-PCK','tool_type','equals',10,true,true),
  ('EQP-ESP-PCK','diameter_mm','range',11,true,false),
  ('EQP-ESP-PCK','compatible_models','in',12,true,false),
  ('EQP-ESP-PCK','material','in',13,true,false),
  ('EQP-ESP-PCK','market_price','range',90,true,false),
  ('EQP-ESP-PCK','availability','equals',91,true,false),
  ('EQP-ESP-PRT','brand_id','equals',1,true,false),
  ('EQP-ESP-PRT','tool_type','equals',10,true,true),
  ('EQP-ESP-PRT','diameter_mm','range',11,true,false),
  ('EQP-ESP-PRT','compatible_models','in',12,true,false),
  ('EQP-ESP-PRT','material','in',13,true,false),
  ('EQP-ESP-PRT','market_price','range',90,true,false),
  ('EQP-ESP-PRT','availability','equals',91,true,false),
  ('EQP-ESP-TMP','brand_id','equals',1,true,false),
  ('EQP-ESP-TMP','tool_type','equals',10,true,true),
  ('EQP-ESP-TMP','diameter_mm','range',11,true,false),
  ('EQP-ESP-TMP','compatible_models','in',12,true,false),
  ('EQP-ESP-TMP','material','in',13,true,false),
  ('EQP-ESP-TMP','market_price','range',90,true,false),
  ('EQP-ESP-TMP','availability','equals',91,true,false),
  ('EQP-ESP-WDT','brand_id','equals',1,true,false),
  ('EQP-ESP-WDT','tool_type','equals',10,true,true),
  ('EQP-ESP-WDT','diameter_mm','range',11,true,false),
  ('EQP-ESP-WDT','compatible_models','in',12,true,false),
  ('EQP-ESP-WDT','material','in',13,true,false),
  ('EQP-ESP-WDT','market_price','range',90,true,false),
  ('EQP-ESP-WDT','availability','equals',91,true,false),
  ('EQP-FIL-CAP','brand_id','equals',1,true,false),
  ('EQP-FIL-CAP','filter_material','equals',10,true,true),
  ('EQP-FIL-CAP','filter_shape','equals',11,true,false),
  ('EQP-FIL-CAP','filter_size','contains',12,true,false),
  ('EQP-FIL-CAP','compatible_brewers','in',13,true,true),
  ('EQP-FIL-CAP','reusable','equals',14,true,true),
  ('EQP-FIL-CAP','market_price','range',90,true,false),
  ('EQP-FIL-CAP','availability','equals',91,true,false),
  ('EQP-FIL-CLT','brand_id','equals',1,true,false),
  ('EQP-FIL-CLT','filter_material','equals',10,true,true),
  ('EQP-FIL-CLT','filter_shape','equals',11,true,false),
  ('EQP-FIL-CLT','filter_size','contains',12,true,false),
  ('EQP-FIL-CLT','compatible_brewers','in',13,true,true),
  ('EQP-FIL-CLT','reusable','equals',14,true,true),
  ('EQP-FIL-CLT','market_price','range',90,true,false),
  ('EQP-FIL-CLT','availability','equals',91,true,false),
  ('EQP-FIL-MET','brand_id','equals',1,true,false),
  ('EQP-FIL-MET','filter_material','equals',10,true,true),
  ('EQP-FIL-MET','filter_shape','equals',11,true,false),
  ('EQP-FIL-MET','filter_size','contains',12,true,false),
  ('EQP-FIL-MET','compatible_brewers','in',13,true,true),
  ('EQP-FIL-MET','reusable','equals',14,true,true),
  ('EQP-FIL-MET','market_price','range',90,true,false),
  ('EQP-FIL-MET','availability','equals',91,true,false),
  ('EQP-FIL-PAP','brand_id','equals',1,true,false),
  ('EQP-FIL-PAP','filter_material','equals',10,true,true),
  ('EQP-FIL-PAP','filter_shape','equals',11,true,false),
  ('EQP-FIL-PAP','filter_size','contains',12,true,false),
  ('EQP-FIL-PAP','compatible_brewers','in',13,true,true),
  ('EQP-FIL-PAP','reusable','equals',14,true,true),
  ('EQP-FIL-PAP','market_price','range',90,true,false),
  ('EQP-FIL-PAP','availability','equals',91,true,false),
  ('EQP-GRD-ELE','brand_id','equals',1,true,false),
  ('EQP-GRD-ELE','grinder_drive','equals',10,true,true),
  ('EQP-GRD-ELE','brew_methods','in',11,true,true),
  ('EQP-GRD-ELE','burr_mechanism','equals',12,true,true),
  ('EQP-GRD-ELE','burr_geometry','equals',13,true,false),
  ('EQP-GRD-ELE','adjustment','equals',14,true,true),
  ('EQP-GRD-ELE','feeding','equals',15,true,false),
  ('EQP-GRD-ELE','burr_size_mm','range',16,true,false),
  ('EQP-GRD-ELE','market_price','range',90,true,false),
  ('EQP-GRD-ELE','availability','equals',91,true,false),
  ('EQP-GRD-MAN','brand_id','equals',1,true,false),
  ('EQP-GRD-MAN','grinder_drive','equals',10,true,true),
  ('EQP-GRD-MAN','brew_methods','in',11,true,true),
  ('EQP-GRD-MAN','burr_mechanism','equals',12,true,true),
  ('EQP-GRD-MAN','burr_geometry','equals',13,true,false),
  ('EQP-GRD-MAN','adjustment','equals',14,true,true),
  ('EQP-GRD-MAN','feeding','equals',15,true,false),
  ('EQP-GRD-MAN','burr_size_mm','range',16,true,false),
  ('EQP-GRD-MAN','market_price','range',90,true,false),
  ('EQP-GRD-MAN','availability','equals',91,true,false),
  ('EQP-KET-ELE','brand_id','equals',1,true,false),
  ('EQP-KET-ELE','kettle_drive','equals',10,true,true),
  ('EQP-KET-ELE','gooseneck','equals',11,true,false),
  ('EQP-KET-ELE','capacity_l','range',12,true,true),
  ('EQP-KET-ELE','temperature_control','equals',13,true,false),
  ('EQP-KET-ELE','temperature_range_c','contains',14,true,false),
  ('EQP-KET-ELE','market_price','range',90,true,false),
  ('EQP-KET-ELE','availability','equals',91,true,false),
  ('EQP-KET-STV','brand_id','equals',1,true,false),
  ('EQP-KET-STV','kettle_drive','equals',10,true,true),
  ('EQP-KET-STV','gooseneck','equals',11,true,false),
  ('EQP-KET-STV','capacity_l','range',12,true,true),
  ('EQP-KET-STV','temperature_control','equals',13,true,false),
  ('EQP-KET-STV','temperature_range_c','contains',14,true,false),
  ('EQP-KET-STV','market_price','range',90,true,false),
  ('EQP-KET-STV','availability','equals',91,true,false),
  ('EQP-MCH-CAP','brand_id','equals',1,true,false),
  ('EQP-MCH-CAP','capsule_system','equals',10,true,true),
  ('EQP-MCH-CAP','milk_system','equals',11,true,false),
  ('EQP-MCH-CAP','water_capacity_l','range',12,true,false),
  ('EQP-MCH-CAP','market_price','range',90,true,false),
  ('EQP-MCH-CAP','availability','equals',91,true,false),
  ('EQP-MCH-ESP','brand_id','equals',1,true,false),
  ('EQP-MCH-ESP','operation_mode','equals',10,true,true),
  ('EQP-MCH-ESP','heating_system','in',11,true,false),
  ('EQP-MCH-ESP','water_source','in',12,true,false),
  ('EQP-MCH-ESP','group_count','range',13,true,false),
  ('EQP-MCH-ESP','application','in',14,true,true),
  ('EQP-MCH-ESP','milk_system','equals',15,true,false),
  ('EQP-MCH-ESP','market_price','range',90,true,false),
  ('EQP-MCH-ESP','availability','equals',91,true,false),
  ('EQP-MCH-FLT','brand_id','equals',1,true,false),
  ('EQP-MCH-FLT','brew_capacity_l','range',10,true,true),
  ('EQP-MCH-FLT','carafe_type','equals',11,true,false),
  ('EQP-MCH-FLT','programmable','equals',12,true,false),
  ('EQP-MCH-FLT','sca_certified','contains',13,true,false),
  ('EQP-MCH-FLT','application','in',14,true,true),
  ('EQP-MCH-FLT','market_price','range',90,true,false),
  ('EQP-MCH-FLT','availability','equals',91,true,false),
  ('EQP-MCH-TRK','brand_id','equals',1,true,false),
  ('EQP-MCH-TRK','cup_capacity','range',10,true,true),
  ('EQP-MCH-TRK','auto_shutoff','equals',11,true,false),
  ('EQP-MCH-TRK','pot_material','equals',12,true,false),
  ('EQP-MCH-TRK','market_price','range',90,true,false),
  ('EQP-MCH-TRK','availability','equals',91,true,false),
  ('EQP-MSR-REF','brand_id','equals',1,true,false),
  ('EQP-MSR-REF','measurement_type','equals',10,true,true),
  ('EQP-MSR-REF','measurement_range','contains',11,true,true),
  ('EQP-MSR-REF','accuracy','range',12,true,false),
  ('EQP-MSR-REF','market_price','range',90,true,false),
  ('EQP-MSR-REF','availability','equals',91,true,false),
  ('EQP-MSR-SCL','brand_id','equals',1,true,false),
  ('EQP-MSR-SCL','resolution_g','range',10,true,true),
  ('EQP-MSR-SCL','capacity_g','range',11,true,true),
  ('EQP-MSR-SCL','timer','equals',12,true,false),
  ('EQP-MSR-SCL','flow_rate','equals',13,true,false),
  ('EQP-MSR-SCL','connectivity','in',14,true,false),
  ('EQP-MSR-SCL','market_price','range',90,true,false),
  ('EQP-MSR-SCL','availability','equals',91,true,false),
  ('EQP-MSR-THM','brand_id','equals',1,true,false),
  ('EQP-MSR-THM','measurement_type','equals',10,true,true),
  ('EQP-MSR-THM','measurement_range','contains',11,true,true),
  ('EQP-MSR-THM','accuracy','range',12,true,false),
  ('EQP-MSR-THM','market_price','range',90,true,false),
  ('EQP-MSR-THM','availability','equals',91,true,false),
  ('EQP-ROA','roaster_technology','equals',201,true,true),
  ('EQP-ROA','batch_capacity_min','range',202,true,false),
  ('EQP-ROA','batch_capacity_max','range',203,true,true),
  ('EQP-ROA','heat_source','equals',204,true,true),
  ('EQP-ROA','electrical_supply','in',205,true,false),
  ('EQP-ROA','rated_power','range',207,true,false),
  ('EQP-ROA','dimensions','contains',208,true,false),
  ('EQP-ROA','net_weight','range',209,true,false),
  ('EQP-ROA','control_mode','in',210,true,false),
  ('EQP-ROA','airflow_control','equals',211,true,false),
  ('EQP-ROA','drum_speed_control','equals',212,true,false),
  ('EQP-ROA','cooling_system','in',213,true,false),
  ('EQP-ROA','profile_connectivity','in',214,true,false),
  ('EQP-ROA','chaff_collection','equals',215,true,false),
  ('EQP-ROA','warranty_months','range',218,true,false),
  ('EQP-ROA','local_service_available','equals',219,true,false),
  ('EQP-ROA','spare_parts_available','equals',220,true,false),
  ('EQP-ROA','installation_required','equals',221,true,false),
  ('EQP-ROA-COM','roaster_use_class','equals',200,true,true),
  ('EQP-ROA-COM','gas_requirement','equals',206,true,false),
  ('EQP-ROA-HOM','roaster_use_class','equals',200,true,true),
  ('EQP-ROA-SMP','brand_id','equals',1,true,false),
  ('EQP-ROA-SMP','market_price','range',90,true,false),
  ('EQP-ROA-SMP','availability','equals',91,true,false),
  ('EQP-ROA-SMP','roaster_use_class','equals',200,true,true),
  ('EQP-SRV-SRV','brand_id','equals',1,true,false),
  ('EQP-SRV-SRV','capacity_ml','range',10,true,true),
  ('EQP-SRV-SRV','material','in',11,true,false),
  ('EQP-SRV-SRV','insulated','equals',12,true,false),
  ('EQP-SRV-SRV','compatible_brewers','in',13,true,false),
  ('EQP-SRV-SRV','market_price','range',90,true,false),
  ('EQP-SRV-SRV','availability','equals',91,true,false),
  ('EQP-SRV-THM','brand_id','equals',1,true,false),
  ('EQP-SRV-THM','capacity_ml','range',10,true,true),
  ('EQP-SRV-THM','material','in',11,true,false),
  ('EQP-SRV-THM','insulated','equals',12,true,false),
  ('EQP-SRV-THM','compatible_brewers','in',13,true,false),
  ('EQP-SRV-THM','market_price','range',90,true,false),
  ('EQP-SRV-THM','availability','equals',91,true,false),
  ('EQP-WCS-CLN','brand_id','equals',1,true,false),
  ('EQP-WCS-CLN','care_task','in',10,true,true),
  ('EQP-WCS-CLN','compatible_equipment','in',11,true,false),
  ('EQP-WCS-CLN','product_form','equals',12,true,true),
  ('EQP-WCS-CLN','market_price','range',90,true,false),
  ('EQP-WCS-CLN','availability','equals',91,true,false),
  ('EQP-WCS-STR','brand_id','equals',1,true,false),
  ('EQP-WCS-STR','storage_type','equals',10,true,true),
  ('EQP-WCS-STR','capacity_g','range',11,true,false),
  ('EQP-WCS-STR','closure','equals',12,true,false),
  ('EQP-WCS-STR','market_price','range',90,true,false),
  ('EQP-WCS-STR','availability','equals',91,true,false),
  ('EQP-WCS-WAT','brand_id','equals',1,true,false),
  ('EQP-WCS-WAT','water_task','in',10,true,true),
  ('EQP-WCS-WAT','compatible_systems','in',11,true,false),
  ('EQP-WCS-WAT','rated_capacity_l','range',12,true,false),
  ('EQP-WCS-WAT','market_price','range',90,true,false),
  ('EQP-WCS-WAT','availability','equals',91,true,false)
)
insert into public.filter_definitions (category_id,field_definition_id,operator,sort_order,is_visible,is_required_for_publish,status)
select c.id,f.id,s.operator,s.sort_order,s.is_visible,s.is_required_for_publish,'published'::public.publication_status
from seed s join public.categories c on c.code=s.category_code join public.field_definitions f on f.code=s.field_code
on conflict (category_id,field_definition_id) do update set operator=excluded.operator, sort_order=excluded.sort_order, is_visible=excluded.is_visible, is_required_for_publish=excluded.is_required_for_publish, status=excluded.status;
comment on table public.categories is 'V1 product taxonomy seeded by migration 002; Green Coffee remains draft/Phase 2.';
commit;
select (select count(*) from public.categories where code in (select unnest(array['COF','EQP','COF-ROASTED','COF-GREEN','EQP-GRD','EQP-GRD-MAN','EQP-GRD-ELE','EQP-MCH','EQP-MCH-ESP','EQP-MCH-FLT','EQP-MCH-TRK','EQP-MCH-CAP','EQP-BRW','EQP-BRW-DRP','EQP-BRW-FRP','EQP-BRW-PRS','EQP-BRW-INT','EQP-BRW-MOK','EQP-BRW-SYP','EQP-BRW-CLD','EQP-BRW-IBR','EQP-BRW-SIF','EQP-BRW-PHN','EQP-KET','EQP-KET-ELE','EQP-KET-STV','EQP-MSR','EQP-MSR-SCL','EQP-MSR-THM','EQP-MSR-REF','EQP-ESP','EQP-ESP-TMP','EQP-ESP-DST','EQP-ESP-WDT','EQP-ESP-KBX','EQP-ESP-PRT','EQP-ESP-MIL','EQP-ESP-DSG','EQP-ESP-PCK','EQP-ESP-MAT','EQP-ESP-MIR','EQP-FIL','EQP-FIL-PAP','EQP-FIL-MET','EQP-FIL-CLT','EQP-FIL-CAP','EQP-SRV','EQP-SRV-SRV','EQP-SRV-THM','EQP-WCS','EQP-WCS-WAT','EQP-WCS-CLN','EQP-WCS-STR','EQP-ROA','EQP-ROA-HOM','EQP-ROA-SMP','EQP-ROA-COM']))) as seeded_categories, (select count(*) from public.field_definitions where status='published') as published_field_definitions, (select count(*) from public.filter_definitions where status='published') as published_filter_links;
-- Seed summary: 57 categories; 90 field definitions; 334 category-filter links.
